chore: fix clippy(beta) error
https://github.com/libp2p/rust-libp2p/actions/runs/21696896538/job/62568845676?pr=6264
> error: the `Err`-variant returned from this closure is very large
> Error:    --> swarm/src/connection/pool.rs:692:41

ref: [result_large_err](https://rust-lang.github.io/rust-clippy/beta/index.html#result_large_err)

Allowed `result_large_err` since the `Result` returned by the closure is [consumed immediately](https://github.com/libp2p/rust-libp2p/blob/3c8c1e30bc81f8297469369789195a2015f3537d/swarm/src/connection/pool.rs#L742-L756), so the large error variant is never propagated across stack frames.

Pull-Request: #6266.